import importlib.util
import sys
from pathlib import Path


def _load_update_current_module():
    script_path = Path(__file__).resolve().parents[1] / "scripts" / "update_current.py"
    spec = importlib.util.spec_from_file_location("update_current_script", script_path)
    assert spec is not None
    assert spec.loader is not None

    module = importlib.util.module_from_spec(spec)
    sys.modules.setdefault("update_current_script", module)
    spec.loader.exec_module(module)
    return module


update_current = _load_update_current_module()
build_expected_current_exports = update_current.build_expected_current_exports
current_exports_are_up_to_date = update_current.current_exports_are_up_to_date
ensure_current_exports_staged = update_current.ensure_current_exports_staged
find_latest_version_dir = update_current.find_latest_version_dir
parse_version_dir_name = update_current.parse_version_dir_name
stage_path = update_current.stage_path
sync_current_exports = update_current.sync_current_exports


def test_parse_version_dir_name() -> None:
    assert parse_version_dir_name("v202602_1") == (202602, 1)
    assert parse_version_dir_name("current") is None
    assert parse_version_dir_name("v20262_1") is None


def test_find_latest_version_dir_prefers_newest_quarter_then_minor(tmp_path: Path) -> None:
    package_dir = tmp_path / "zuu"
    package_dir.mkdir()
    (package_dir / "v202601_9").mkdir()
    (package_dir / "v202602_1").mkdir()
    (package_dir / "v202602_3").mkdir()

    latest_dir = find_latest_version_dir(package_dir)

    assert latest_dir.name == "v202602_3"


def test_sync_current_exports_rebuilds_current_from_latest_version(tmp_path: Path) -> None:
    package_dir = tmp_path / "zuu"
    package_dir.mkdir()

    old_version_dir = package_dir / "v202601_1"
    old_version_dir.mkdir()
    (old_version_dir / "__init__.py").write_text("", encoding="utf-8")
    (old_version_dir / "detect_editor.py").write_text("OLD = True\n", encoding="utf-8")

    latest_version_dir = package_dir / "v202602_2"
    latest_version_dir.mkdir()
    (latest_version_dir / "__init__.py").write_text("", encoding="utf-8")
    (latest_version_dir / "detect_editor.py").write_text("LATEST = True\n", encoding="utf-8")
    nested_package_dir = latest_version_dir / "subpkg"
    nested_package_dir.mkdir()
    (nested_package_dir / "__init__.py").write_text("", encoding="utf-8")
    (nested_package_dir / "helpers.py").write_text("HELPER = True\n", encoding="utf-8")

    current_dir = package_dir / "current"
    current_dir.mkdir()
    (current_dir / "stale.py").write_text("stale\n", encoding="utf-8")

    latest_dir = sync_current_exports(package_dir)

    assert latest_dir.name == "v202602_2"
    assert (current_dir / "stale.py").exists() is False
    assert (current_dir / "__init__.py").exists() is False
    assert (current_dir / "detect_editor.py").read_text(encoding="utf-8") == (
        "# Generated by scripts/update_current.py. Do not edit manually.\n"
        "from zuu.v202602_2.detect_editor import *  # noqa: F403\n"
    )
    assert (current_dir / "subpkg" / "__init__.py").exists() is False
    assert (current_dir / "subpkg" / "helpers.py").read_text(encoding="utf-8") == (
        "# Generated by scripts/update_current.py. Do not edit manually.\n"
        "from zuu.v202602_2.subpkg.helpers import *  # noqa: F403\n"
    )

    for generated_file in current_dir.rglob("*.py"):
        assert "zuu.current" not in generated_file.read_text(encoding="utf-8")


def test_build_expected_current_exports_skips_dunder_files(tmp_path: Path) -> None:
    package_dir = tmp_path / "zuu"
    latest_version_dir = package_dir / "v202602_2"
    latest_version_dir.mkdir(parents=True)
    (latest_version_dir / "__init__.py").write_text("", encoding="utf-8")
    (latest_version_dir / "detect_editor.py").write_text("LATEST = True\n", encoding="utf-8")

    latest_dir, expected_exports = build_expected_current_exports(package_dir)

    assert latest_dir.name == "v202602_2"
    assert Path("__init__.py") not in expected_exports
    assert expected_exports[Path("detect_editor.py")] == (
        "# Generated by scripts/update_current.py. Do not edit manually.\n"
        "from zuu.v202602_2.detect_editor import *  # noqa: F403\n"
    )


def test_current_exports_are_up_to_date_detects_stale_current(tmp_path: Path) -> None:
    package_dir = tmp_path / "zuu"
    latest_version_dir = package_dir / "v202602_2"
    latest_version_dir.mkdir(parents=True)
    (latest_version_dir / "detect_editor.py").write_text("LATEST = True\n", encoding="utf-8")

    current_dir = package_dir / "current"
    current_dir.mkdir()
    (current_dir / "detect_editor.py").write_text("stale\n", encoding="utf-8")

    is_up_to_date, latest_dir = current_exports_are_up_to_date(package_dir)

    assert is_up_to_date is False
    assert latest_dir.name == "v202602_2"


def test_current_exports_are_up_to_date_accepts_fresh_current(tmp_path: Path) -> None:
    package_dir = tmp_path / "zuu"
    latest_version_dir = package_dir / "v202602_2"
    latest_version_dir.mkdir(parents=True)
    (latest_version_dir / "detect_editor.py").write_text("LATEST = True\n", encoding="utf-8")

    sync_current_exports(package_dir)

    is_up_to_date, latest_dir = current_exports_are_up_to_date(package_dir)

    assert is_up_to_date is True
    assert latest_dir.name == "v202602_2"


def test_ensure_current_exports_staged_regenerates_and_stages_when_stale(tmp_path: Path, monkeypatch) -> None:
    package_dir = tmp_path / "src" / "zuu"
    latest_version_dir = package_dir / "v202602_2"
    latest_version_dir.mkdir(parents=True)
    (latest_version_dir / "detect_editor.py").write_text("LATEST = True\n", encoding="utf-8")

    current_dir = package_dir / "current"
    current_dir.mkdir()
    (current_dir / "detect_editor.py").write_text("stale\n", encoding="utf-8")
    repository_root = tmp_path
    staged_paths: list[str] = []

    monkeypatch.setattr(update_current, "stage_path", lambda root, relative_path: staged_paths.append(relative_path))

    changed, latest_dir = ensure_current_exports_staged(package_dir, repository_root)

    assert changed is True
    assert latest_dir.name == "v202602_2"
    assert staged_paths == ["src/zuu/current"]
    assert (current_dir / "detect_editor.py").read_text(encoding="utf-8") == (
        "# Generated by scripts/update_current.py. Do not edit manually.\n"
        "from zuu.v202602_2.detect_editor import *  # noqa: F403\n"
    )


def test_ensure_current_exports_staged_noops_when_current_is_fresh(tmp_path: Path, monkeypatch) -> None:
    package_dir = tmp_path / "src" / "zuu"
    latest_version_dir = package_dir / "v202602_2"
    latest_version_dir.mkdir(parents=True)
    (latest_version_dir / "detect_editor.py").write_text("LATEST = True\n", encoding="utf-8")

    sync_current_exports(package_dir)
    staged_paths: list[str] = []
    monkeypatch.setattr(update_current, "stage_path", lambda root, relative_path: staged_paths.append(relative_path))

    changed, latest_dir = ensure_current_exports_staged(package_dir, tmp_path)

    assert changed is False
    assert latest_dir.name == "v202602_2"
    assert staged_paths == []