import importlib.util
import sys
from pathlib import Path


def _load_update_current_module():
    script_path = Path(__file__).resolve().parents[1] / "scripts" / "update_current.py"
    spec = importlib.util.spec_from_file_location("update_current_script", script_path)
    assert spec is not None
    assert spec.loader is not None

    module = importlib.util.module_from_spec(spec)
    sys.modules.setdefault("update_current_script", module)
    spec.loader.exec_module(module)
    return module


update_current = _load_update_current_module()
find_latest_version_dir = update_current.find_latest_version_dir
parse_version_dir_name = update_current.parse_version_dir_name
sync_current_exports = update_current.sync_current_exports


def test_parse_version_dir_name() -> None:
    assert parse_version_dir_name("v202602_1") == (202602, 1)
    assert parse_version_dir_name("current") is None
    assert parse_version_dir_name("v20262_1") is None


def test_find_latest_version_dir_prefers_newest_quarter_then_minor(tmp_path: Path) -> None:
    package_dir = tmp_path / "zuu"
    package_dir.mkdir()
    (package_dir / "v202601_9").mkdir()
    (package_dir / "v202602_1").mkdir()
    (package_dir / "v202602_3").mkdir()

    latest_dir = find_latest_version_dir(package_dir)

    assert latest_dir.name == "v202602_3"


def test_sync_current_exports_rebuilds_current_from_latest_version(tmp_path: Path) -> None:
    package_dir = tmp_path / "zuu"
    package_dir.mkdir()

    old_version_dir = package_dir / "v202601_1"
    old_version_dir.mkdir()
    (old_version_dir / "__init__.py").write_text("", encoding="utf-8")
    (old_version_dir / "detect_editor.py").write_text("OLD = True\n", encoding="utf-8")

    latest_version_dir = package_dir / "v202602_2"
    latest_version_dir.mkdir()
    (latest_version_dir / "__init__.py").write_text("", encoding="utf-8")
    (latest_version_dir / "detect_editor.py").write_text("LATEST = True\n", encoding="utf-8")
    nested_package_dir = latest_version_dir / "subpkg"
    nested_package_dir.mkdir()
    (nested_package_dir / "__init__.py").write_text("", encoding="utf-8")
    (nested_package_dir / "helpers.py").write_text("HELPER = True\n", encoding="utf-8")

    current_dir = package_dir / "current"
    current_dir.mkdir()
    (current_dir / "stale.py").write_text("stale\n", encoding="utf-8")

    latest_dir = sync_current_exports(package_dir)

    assert latest_dir.name == "v202602_2"
    assert (current_dir / "stale.py").exists() is False
    assert (current_dir / "__init__.py").exists() is False
    assert (current_dir / "detect_editor.py").read_text(encoding="utf-8") == (
        "# Generated by scripts/update_current.py. Do not edit manually.\n"
        "from zuu.v202602_2.detect_editor import *  # noqa: F403\n"
    )
    assert (current_dir / "subpkg" / "__init__.py").exists() is False
    assert (current_dir / "subpkg" / "helpers.py").read_text(encoding="utf-8") == (
        "# Generated by scripts/update_current.py. Do not edit manually.\n"
        "from zuu.v202602_2.subpkg.helpers import *  # noqa: F403\n"
    )

    for generated_file in current_dir.rglob("*.py"):
        assert "zuu.current" not in generated_file.read_text(encoding="utf-8")