import argparse
import re
import shutil
from pathlib import Path


VERSION_DIR_PATTERN = re.compile(r"^v(?P<yearquarter>\d{6})_(?P<minor>\d+)$")


def parse_version_dir_name(name: str) -> tuple[int, int] | None:
    match = VERSION_DIR_PATTERN.fullmatch(name)
    if match is None:
        return None

    return int(match.group("yearquarter")), int(match.group("minor"))


def find_latest_version_dir(package_dir: Path) -> Path:
    version_dirs = [
        child
        for child in package_dir.iterdir()
        if child.is_dir() and parse_version_dir_name(child.name) is not None
    ]

    if not version_dirs:
        raise FileNotFoundError(f"No version directories found in {package_dir}")

    return max(version_dirs, key=lambda child: parse_version_dir_name(child.name))


def render_export_module(package_name: str, version_name: str, module_parts: tuple[str, ...]) -> str:
    target_module = ".".join((package_name, version_name, *module_parts))
    return (
        "# Generated by scripts/update_current.py. Do not edit manually.\n"
        f"from {target_module} import *  # noqa: F403\n"
    )


def _iter_python_files(root_dir: Path) -> list[Path]:
    return sorted(
        path
        for path in root_dir.rglob("*.py")
        if "__pycache__" not in path.parts and not path.name.startswith("__")
    )


def sync_current_exports(package_dir: Path) -> Path:
    package_dir = package_dir.resolve()
    latest_dir = find_latest_version_dir(package_dir)
    current_dir = package_dir / "current"

    if current_dir.exists():
        shutil.rmtree(current_dir)
    current_dir.mkdir(parents=True, exist_ok=True)

    for source_path in _iter_python_files(latest_dir):
        relative_path = source_path.relative_to(latest_dir)
        module_path = relative_path.with_suffix("")
        module_parts = module_path.parts
        output_path = current_dir / relative_path
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            render_export_module(package_dir.name, latest_dir.name, module_parts),
            encoding="utf-8",
        )

    return latest_dir


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate zuu.current as a thin export layer for the newest versioned package.",
    )
    parser.add_argument(
        "--package-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "src" / "zuu",
        help="Path to the zuu package directory that contains versioned folders.",
    )
    args = parser.parse_args()

    latest_dir = sync_current_exports(args.package_dir)
    print(latest_dir.name)


if __name__ == "__main__":
    main()