import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path


VERSION_DIR_PATTERN = re.compile(r"^v(?P<yearquarter>\d{6})_(?P<minor>\d+)$")


def parse_version_dir_name(name: str) -> tuple[int, int] | None:
    match = VERSION_DIR_PATTERN.fullmatch(name)
    if match is None:
        return None

    return int(match.group("yearquarter")), int(match.group("minor"))


def find_latest_version_dir(package_dir: Path) -> Path:
    version_dirs = [
        child
        for child in package_dir.iterdir()
        if child.is_dir() and parse_version_dir_name(child.name) is not None
    ]

    if not version_dirs:
        raise FileNotFoundError(f"No version directories found in {package_dir}")

    def version_key(child: Path) -> tuple[int, int]:
        parsed_version = parse_version_dir_name(child.name)
        if parsed_version is None:
            raise ValueError(f"Invalid version directory name: {child.name}")

        return parsed_version

    return max(version_dirs, key=version_key)


def render_export_module(package_name: str, version_name: str, module_parts: tuple[str, ...]) -> str:
    target_module = ".".join((package_name, version_name, *module_parts))
    return (
        "# Generated by scripts/update_current.py. Do not edit manually.\n"
        f"from {target_module} import *  # noqa: F403\n"
    )


def _iter_python_files(root_dir: Path) -> list[Path]:
    return sorted(
        path
        for path in root_dir.rglob("*.py")
        if "__pycache__" not in path.parts and not path.name.startswith("__")
    )


def build_expected_current_exports(package_dir: Path) -> tuple[Path, dict[Path, str]]:
    package_dir = package_dir.resolve()
    latest_dir = find_latest_version_dir(package_dir)
    expected_exports: dict[Path, str] = {}

    for source_path in _iter_python_files(latest_dir):
        relative_path = source_path.relative_to(latest_dir)
        module_path = relative_path.with_suffix("")
        expected_exports[relative_path] = render_export_module(
            package_dir.name,
            latest_dir.name,
            module_path.parts,
        )

    return latest_dir, expected_exports


def read_current_exports(current_dir: Path) -> dict[Path, str]:
    if not current_dir.exists():
        return {}

    return {
        path.relative_to(current_dir): path.read_text(encoding="utf-8")
        for path in sorted(path for path in current_dir.rglob("*.py") if "__pycache__" not in path.parts)
    }


def current_exports_are_up_to_date(package_dir: Path) -> tuple[bool, Path]:
    package_dir = package_dir.resolve()
    latest_dir, expected_exports = build_expected_current_exports(package_dir)
    actual_exports = read_current_exports(package_dir / "current")
    return actual_exports == expected_exports, latest_dir


def run_git_command(repository_root: Path, args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repository_root), *args],
        capture_output=True,
        check=False,
        text=True,
    )


def _raise_for_failed_git_command(
    repository_root: Path,
    command_description: str,
    result: subprocess.CompletedProcess[str],
) -> None:
    if result.returncode == 0:
        return

    message = result.stderr.strip() or result.stdout.strip() or f"exit code {result.returncode}"
    raise RuntimeError(f"{command_description} failed for {repository_root}: {message}")


def stage_path(repository_root: Path, relative_path: str) -> None:
    result = run_git_command(repository_root, ["add", "--all", "--", relative_path])
    _raise_for_failed_git_command(repository_root, f"git add --all {relative_path}", result)


def sync_current_exports(package_dir: Path) -> Path:
    package_dir = package_dir.resolve()
    latest_dir, expected_exports = build_expected_current_exports(package_dir)
    current_dir = package_dir / "current"

    if current_dir.exists():
        shutil.rmtree(current_dir)
    current_dir.mkdir(parents=True, exist_ok=True)

    for relative_path, content in expected_exports.items():
        output_path = current_dir / relative_path
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")

    return latest_dir


def ensure_current_exports_staged(package_dir: Path, repository_root: Path) -> tuple[bool, Path]:
    is_up_to_date, latest_dir = current_exports_are_up_to_date(package_dir)
    if is_up_to_date:
        return False, latest_dir

    sync_current_exports(package_dir)
    stage_path(repository_root, (package_dir / "current").relative_to(repository_root).as_posix())
    return True, latest_dir


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate zuu.current as a thin export layer for the newest versioned package.",
    )
    parser.add_argument(
        "--package-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "src" / "zuu",
        help="Path to the zuu package directory that contains versioned folders.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with a non-zero status when src/zuu/current is not aligned to the latest versioned package.",
    )
    parser.add_argument(
        "--ensure-staged",
        action="store_true",
        help="Regenerate src/zuu/current and stage it when it is out of date.",
    )
    args = parser.parse_args()

    if args.check and args.ensure_staged:
        raise ValueError("Choose either --check or --ensure-staged, not both.")

    if args.check:
        is_up_to_date, latest_dir = current_exports_are_up_to_date(args.package_dir)
        if not is_up_to_date:
            print(
                f"src/zuu/current is out of date for {latest_dir.name}. Run: uv run python scripts/update_current.py",
                file=sys.stderr,
            )
            raise SystemExit(1)

        print(latest_dir.name)
        return

    if args.ensure_staged:
        repository_root = args.package_dir.resolve().parent.parent
        changed, latest_dir = ensure_current_exports_staged(args.package_dir, repository_root)
        if changed:
            print(f"Automatically refreshed and staged src/zuu/current for {latest_dir.name}.")
        else:
            print(latest_dir.name)
        return

    latest_dir = sync_current_exports(args.package_dir)
    print(latest_dir.name)


if __name__ == "__main__":
    main()